version: "3.7"

services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - /home/joao/Documents/mosquitto/config:/mosquitto/config
      - /home/joao/Documents/mosquitto/data:/mosquitto/data
      - /home/joao/Documents/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    networks:
      - intnet

networks:
  intnet:
