site_name: Simulação IoT
theme:
  name: material
  features:
    - content.code.annotate

nav:
  - Introdução: index.md
  - Servidor MQTT: broker.md
  - Estrutura de Pastas: path.md

  - Código para Simulação: code.md
  - Definindo tamanho de amostra: tamanho_da_amos.md
  - Analisando Amostra piloto: analise_amostra_piloto.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

dev_addr: '0.0.0.0:8086'
